import CustomCursor from '@/components/CustomCursor/CustomCursor';
import InitialLoader from '@/components/InitialLoader/InitialLoader';
import UnregisterServiceWorkers from '@/components/UnregisterServiceWorkers';
import { DeviceProvider } from '@/context/DeviceProvider';
import { ScrollProvider } from '@/context/ScrollProvider';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Libre_Baskerville, Roboto } from 'next/font/google';
import Script from 'next/script';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const libreBaskerville = Libre_Baskerville({
  variable: '--font-libre-baskerville',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Vault',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          roboto.variable,
          libreBaskerville.variable,
        ].join(' ')}
      >
        <Script
          id="unregister-sw-dev"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined' && window.location?.hostname === 'localhost' && 'serviceWorker' in navigator) {
                navigator.serviceWorker.getRegistrations().then(function(regs) {
                  regs.forEach(function(r) { r.unregister(); });
                });
              }
            `,
          }}
        />
        <DeviceProvider>
          <ScrollProvider>
            <UnregisterServiceWorkers />
            <CustomCursor />
            <InitialLoader />
            {children}
          </ScrollProvider>
        </DeviceProvider>
      </body>
    </html>
  );
}
